# Generated by Django 4.0.3 on 2022-10-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunbae', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(max_length=50)),
            ],
        ),
    ]
