# Generated by Django 4.0.3 on 2022-10-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunbae', '0002_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='api',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
