# Generated by Django 4.0.3 on 2022-10-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunbae', '0003_rename_test_signin_delete_answer_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherKey', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('id', models.CharField(max_length=50)),
                ('part', models.CharField(max_length=10)),
                ('resSubject', models.CharField(max_length=10)),
                ('joinDate', models.DateTimeField(auto_now_add=True)),
                ('leaveDate', models.DateTimeField(auto_now=True)),
                ('resume', models.CharField(max_length=50)),
                ('profileImg', models.CharField(max_length=50)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('editDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='api',
        ),
    ]
