# Generated by Django 4.0.3 on 2022-10-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminKey', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('id', models.CharField(max_length=50)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('editDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
